### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by websitesupport** [Automattic/eventbrite-api#24]
Hi,
I got the template running, but the title and image are taking me to another page in the website, generated by the template. How can I link them straight to the eventbrite page?

**Comment by jacoblindgren** [comment]
Sorry to resurrect this issue, but I'm encountering the same problem and can't gather what the solution was. I'm viewing inc/functions.php and can see on line 190:

`$url = add_query_arg( array( 'ref' => 'wporglink' ), eventbrite_event_eb_url() );`

What do I need to do here in order to prevent the clicking of event titles/photos to go to the WP generated page, but instead the Eventbrite page (or ideally do nothing)? Thanks for the help.
