### ISSUE TITLE
iframe size

### ISSUE THREAD

**Issue by MMBarsoum** [Automattic/eventbrite-api#72]
Hi, for some reason when I install the API and Keyring, I can only see a few lines of the amount of ticket types I'm selling. It's a small iframe (or so it seems) and I have to scroll within that embedded window to access the whole list. Is there a way to automatically make it change according to the ticket types available for sale?
![screenshot 2017-11-30 23 27 36](https://user-images.githubusercontent.com/34150402/33467903-2c70f19a-d626-11e7-8a92-5dd0f33db6e2.png)

**Comment by kwight** [comment]
Sadly, there isn't a simple, automatic way to cover all variations of ticket numbers and types. Since it's an iframe, the server isn't aware of the size of the content it contains, so [it needs to make an educated guess](https://github.com/Automattic/eventbrite-api/blob/master/inc/functions.php#L422). There's [a filter](https://github.com/Automattic/eventbrite-api/blob/master/inc/functions.php#L472) to make adjustments on a per-site basis; the other option is to work something out JavaScript-wise in the client, but we have no plans of tackling that (both options will require a developer). Hope this helps.
